### ISSUE TITLE
Compatibility issue with ArtificerExtended

### ISSUE THREAD

**Issue by Cuddlebean** [yekoc/Risk-Of-Rain-2-Mods#1]
After some testing I've noticed that when used with ArtificerExtended, Unorthodox Rituals is split into a separate category in the loadout screen.
**Without ArtificerExtended:**
![Without ArtificerExtended](https://user-images.githubusercontent.com/122710006/212520504-667d3d5c-2cba-43d6-85e1-0fd832f523a2.png)
**With ArtificerExtended:**
![WithArtificerExtended](https://user-images.githubusercontent.com/122710006/212520509-d37c6a9a-883d-4449-aeb7-fd98234a5390.png)

**Comment by yekoc** [comment]
This is mostly a visual issue,since only one of the passives can be active due to the way they are coded.
I will be looking into manually overriding AE's skill family shifting,which is what causes this since it doesn't rename the families.

**Comment by yekoc** [comment]
Closing since Artificer Extended got deprecated and the visual inconsistency is no longer as important.
