### ISSUE TITLE
Question: Where is the save file location is at? 

### ISSUE THREAD

**Issue by KaitoXion** [yekoc/Risk-Of-Rain-2-Mods#10]
Hi,

A humble question from me. I did like to inquire about;
 - Where is the save file location is set to save at?
 - Is it possible to manually change the save location to save as the game folder? For example, via .cfg file.
 
 Look forward to your kind expert comment.
 Thanks a bunch for taking your time to read this.

**Comment by yekoc** [comment]
If you mean this in regards to CompactSave it doesn't change the game's save location.
By default, the games saves should be under your steam userdata folder with the game's id (632360).
As far as I'm aware, the location is determined by steam,however you _should_ be able to set the relevant folder to be a filesystem link to any other location of your choice and it should work.
