### ISSUE TITLE
[MinionOrdering] Multiplayer host using the "order all" button also selects other players' minions who can't be ordered

### ISSUE THREAD

**Issue by LordVGames** [yekoc/Risk-Of-Rain-2-Mods#11]
If a client uses the "order all" button, they can only select their own minions, or none if they don't have any. The selected minions of other clients are also unable to be ordered, since they'll only listen to their owner, not the host. But since the minions are waiting on the host to give an order, they are forever waiting for a command.

**Comment by yekoc** [comment]
Should be fixed in the release that just went out (1.1.1). Please re-open if the issue persists.
Thanks for the report!
