### ISSUE TITLE
Passive: Field Tinkering Removes Sprint Functionality

### ISSUE THREAD

**Issue by cesmaster644** [yekoc/Risk-Of-Rain-2-Mods#4]
I'm running a fair bit of other mods alongside Passive Aggression, so I'm uncertain if it's a compatibility thing. But simply swapping to no-passive from Field Tinkering re-enables sprint for Engineer, so I'm pretty sure that's what's causing it. If that's intentional, it's an odd choice, but fair. It just doesn't seem to be intended, or at least isn't communicated as such.
[zipped_log.zip](https://github.com/yekoc/Risk-Of-Rain-2-Mods/files/10610912/zipped_log.zip)

**Comment by yekoc** [comment]
Very much unintended,very much a compatibility issue.
Log is pretty much useless due to being flooded with a repeating message from another mod,but still thanks for reporting.

**Comment by yekoc** [comment]
@cesmaster644 this is caused by HuntressBuffUltimate.
Not actually a bug because it's apparently intended behavior that that mod changes what the flags on the skilldef mean.
