### ISSUE TITLE
Engineer Cascading Resonance Frame Drops

### ISSUE THREAD

**Issue by OldManFortran** [yekoc/Risk-Of-Rain-2-Mods#9]
In multiplayer, using Cascading Resonance as a client functions, but causes game lag/frame drops very quickly. 

Here is my log file, this file is for only about 5 seconds of playing a round, playing for only a couple of minutes makes the log file generated too large to upload (I have had a log file as large as 2.23 Gigabytes) and the majority of the content of the log files are always the error that i have pasted below.

[Player.log](https://github.com/yekoc/Risk-Of-Rain-2-Mods/files/12270430/Player.log)

```
NullReferenceException: Object reference not set to an instance of an object
  at PassiveAgression.Engineer.ResonancePrimary+EnemyResonatingState.FixedUpdate () [0x00067] in <18bfe958f76b44ef8ee232eb3010f722>:IL_0067 
  at RoR2.EntityStateMachine.FixedUpdate () [0x0001a] in <abee4f3b46184662b4d0bd0bc9965114>:IL_001A 

(Filename: <18bfe958f76b44ef8ee232eb3010f722> Line: 0) 
```

**Comment by yekoc** [comment]
Thanks for the report,should be fixed in the next release.

**Comment by yekoc** [comment]
New release is out,please re-open if the issue persists.
